# Generated by Django 2.1.15 on 2020-04-27 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=140, verbose_name='보기 문항')),
                ('count', models.IntegerField(default=0, verbose_name='투표수')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Vote')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=140, verbose_name='댓글')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='댓글 생성 시간')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Choice')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='votes.Vote')),
            ],
        ),
    ]
