# Generated by Django 2.1.15 on 2020-04-27 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0003_auto_20200427_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice1',
            old_name='choice_text',
            new_name='choice_text1',
        ),
        migrations.RenameField(
            model_name='choice2',
            old_name='choice_text',
            new_name='choice_text2',
        ),
    ]
