# Generated by Django 2.1.15 on 2020-04-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_auto_20200427_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='choice',
            field=models.CharField(choices=[('보기1', '보기1'), ('보기2', '보기2')], max_length=140, verbose_name='선택'),
        ),
    ]
