# Generated by Django 2.1.15 on 2020-05-13 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='like_users',
            field=models.ManyToManyField(related_name='like_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('SF', 'SF'), ('멜로', '멜로'), ('액션', '액션'), ('코미디', '코미디'), ('스릴러', '스릴러'), ('음악/뮤지컬', '음악/뮤지컬'), ('판타지', '판타지')], max_length=7),
        ),
    ]
